# Generated by Django 5.0.14 on 2026-02-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador único del documento (ej: DOC-001)', max_length=50, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('doc_type', models.CharField(choices=[('MANUAL', 'Manual'), ('PROCEDURE', 'Procedimiento'), ('INSTRUCTION', 'Instructivo'), ('FORMAT', 'Formato'), ('EXTERNAL', 'Externo')], max_length=20, verbose_name='Tipo de documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.process', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Ej: 1.0, 2.1, etc.', max_length=20, verbose_name='Número de versión')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('effective_date', models.DateField(verbose_name='Fecha de vigencia')),
                ('review_due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de revisión próxima')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('OBSOLETE', 'Obsoleto')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Versión de documento',
                'verbose_name_plural': 'Versiones de documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(verbose_name='Aprobado el')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_versions', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='docs.documentversion', verbose_name='Versión de documento')),
            ],
            options={
                'verbose_name': 'Aprobación de documento',
                'verbose_name_plural': 'Aprobaciones de documentos',
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_doc_version_number'),
        ),
    ]
