# Generated by Django 5.0.14 on 2026-01-29 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Tipo de acción realizada', max_length=100, verbose_name='Acción')),
                ('object_type', models.CharField(help_text='Tipo de objeto afectado', max_length=100, verbose_name='Tipo de objeto')),
                ('object_id', models.PositiveIntegerField(help_text='ID del objeto afectado', verbose_name='ID de objeto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('metadata', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Metadatos')),
                ('actor', models.ForeignKey(help_text='Usuario que ejecutó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
