# Generated by Django 5.0.14 on 2026-02-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['code'], 'verbose_name': 'Proceso', 'verbose_name_plural': 'Procesos'},
        ),
        migrations.AlterField(
            model_name='process',
            name='code',
            field=models.CharField(help_text='Identificador único del proceso (ej: CAL, VEN, etc.)', max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre'),
        ),
    ]
