# Generated by Django 5.0.14 on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion


def create_org_and_update_processes(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Process = apps.get_model("core", "Process")

    organization, _created = Organization.objects.get_or_create(
        name="Empresa",
        defaults={"is_active": True},
    )

    Process.objects.filter(organization__isnull=True).update(
        organization=organization,
        process_type="MISSIONAL",
        level=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_process_options_alter_process_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Nombre legal o comercial de la empresa.", max_length=150, unique=True, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Organizacion",
                "verbose_name_plural": "Organizaciones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Nombre de la sede o ubicacion.", max_length=150, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sites", to="core.organization", verbose_name="Organizacion")),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="process",
            name="code",
            field=models.CharField(help_text="Identificador del proceso (ej: 09, 01, C1).", max_length=30, verbose_name="Codigo"),
        ),
        migrations.AlterField(
            model_name="process",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="process",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="process",
            name="level",
            field=models.PositiveSmallIntegerField(choices=[(1, "Proceso"), (2, "Subproceso"), (3, "Sector")], null=True, verbose_name="Nivel"),
        ),
        migrations.AddField(
            model_name="process",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="processes", to="core.organization", verbose_name="Organizacion"),
        ),
        migrations.AddField(
            model_name="process",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="core.process", verbose_name="Proceso padre"),
        ),
        migrations.AddField(
            model_name="process",
            name="process_type",
            field=models.CharField(choices=[("STRATEGIC", "Estrategico"), ("MISSIONAL", "Misional"), ("SUPPORT", "Soporte")], max_length=20, null=True, verbose_name="Tipo de proceso"),
        ),
        migrations.AddField(
            model_name="process",
            name="site",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processes", to="core.site", verbose_name="Sede"),
        ),
        migrations.RunPython(create_org_and_update_processes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="process",
            name="level",
            field=models.PositiveSmallIntegerField(choices=[(1, "Proceso"), (2, "Subproceso"), (3, "Sector")], verbose_name="Nivel"),
        ),
        migrations.AlterField(
            model_name="process",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="processes", to="core.organization", verbose_name="Organizacion"),
        ),
        migrations.AlterField(
            model_name="process",
            name="process_type",
            field=models.CharField(choices=[("STRATEGIC", "Estrategico"), ("MISSIONAL", "Misional"), ("SUPPORT", "Soporte")], max_length=20, verbose_name="Tipo de proceso"),
        ),
        migrations.AddConstraint(
            model_name="process",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="unique_process_code_per_org"),
        ),
    ]
