# Generated by Django 5.0.14 on 2026-02-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_riskopportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcontext',
            options={'verbose_name': 'Contexto de la organizacion', 'verbose_name_plural': 'Contextos de la organizacion'},
        ),
    ]
