# Generated by Django 5.0.14 on 2026-02-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_organizationcontext_options'),
        ('docs', '0002_document_processes_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('origin', models.CharField(choices=[('AUDIT', 'Auditoria'), ('CUSTOMER', 'Cliente'), ('INTERNAL', 'Interna'), ('PRODUCTION', 'Produccion'), ('OTHER', 'Otro')], max_length=20, verbose_name='Origen')),
                ('severity', models.CharField(choices=[('MINOR', 'Menor'), ('MAJOR', 'Mayor'), ('CRITICAL', 'Critica')], max_length=20, verbose_name='Severidad')),
                ('detected_at', models.DateField(help_text='Fecha en la que se detecto la no conformidad', verbose_name='Fecha deteccion')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha limite')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('ANALYSIS', 'En analisis'), ('ACTION', 'En accion'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities_as_evidence', to='docs.document', verbose_name='Documento evidencia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformities', to='core.organization', verbose_name='Organizacion')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities_as_related', to='docs.document', verbose_name='Documento relacionado')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='core.process', verbose_name='Proceso relacionado')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='core.site', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'No conformidad',
                'verbose_name_plural': 'No conformidades',
                'ordering': ['-updated_at'],
            },
        ),
    ]
