# Generated by Django 5.0.14 on 2026-02-13 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_noconformity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformity',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='NC-2025-001, NC-2025-002, etc.', max_length=20, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='corrective_action',
            field=models.TextField(blank=True, help_text='Que se hara para evitar que vuelva a ocurrir?', verbose_name='Accion correctiva'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='detected_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que detecto la no conformidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='Detectado por'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='is_effective',
            field=models.BooleanField(default=False, help_text='La accion correctiva funciono?', verbose_name='Accion efectiva?'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='root_cause_analysis',
            field=models.TextField(blank=True, help_text='Por que ocurrio la NC? Usar 5 Por ques, Ishikawa, etc.', verbose_name='Analisis de causa raiz'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='verification_date',
            field=models.DateField(blank=True, help_text='Fecha en la que se verifico la eficacia de la accion', null=True, verbose_name='Fecha de verificacion'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas de verificacion'),
        ),
        migrations.AlterField(
            model_name='noconformity',
            name='origin',
            field=models.CharField(choices=[('INTERNAL_AUDIT', 'Auditoria interna'), ('EXTERNAL_AUDIT', 'Auditoria externa'), ('CUSTOMER', 'Cliente'), ('INTERNAL', 'Interna'), ('PRODUCTION', 'Produccion'), ('SUPPLIER', 'Proveedor'), ('OTHER', 'Otro')], max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='noconformity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('IN_ANALYSIS', 'En analisis'), ('IN_TREATMENT', 'En tratamiento'), ('VERIFICATION', 'En verificacion'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=20, verbose_name='Estado'),
        ),
    ]
