# Generated by Django 5.0.14 on 2026-02-13 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_nc_field_lengths'),
        ('docs', '0002_document_processes_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descripcion breve de la accion', max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion detallada')),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Correctiva'), ('CONTAINMENT', 'Contencion'), ('PREVENTIVE', 'Preventiva')], default='CORRECTIVE', max_length=20, verbose_name='Tipo de accion')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha limite')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Completada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada el')),
                ('completion_notes', models.TextField(blank=True, help_text='Detalles sobre como se completo la accion', verbose_name='Notas de completitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_actions_as_evidence', to='docs.document', verbose_name='Documento evidencia')),
                ('no_conformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_actions', to='core.noconformity', verbose_name='No conformidad')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_actions', to='core.organization', verbose_name='Organizacion')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Accion CAPA',
                'verbose_name_plural': 'Acciones CAPA',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
