# Generated by Django 5.0.14 on 2026-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_capa_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformity',
            name='severity_score',
            field=models.IntegerField(default=0, editable=False, help_text='Puntuación automática basada en severidad (1=Menor, 2=Mayor, 3=Crítica)', verbose_name='Score de criticidad'),
        ),
    ]
