# Generated by Django 5.0.14 on 2026-02-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_noconformity_severity_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('indicator', models.CharField(help_text='Ej: % entregas en termino', max_length=200, verbose_name='Indicador')),
                ('target_value', models.FloatField(help_text='Valor objetivo a alcanzar', verbose_name='Valor meta')),
                ('current_value', models.FloatField(default=0, verbose_name='Valor actual')),
                ('unit', models.CharField(help_text='Ej: %, días, unidades, horas', max_length=50, verbose_name='Unidad')),
                ('frequency', models.CharField(help_text='Mensual, Trimestral, Anual, etc.', max_length=100, verbose_name='Frecuencia')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('due_date', models.DateField(verbose_name='Fecha vencimiento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('ACHIEVED', 'Cumplido'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='ACTIVE', editable=False, max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_objectives', to='core.organization', verbose_name='Organizacion')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_objectives', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_objectives', to='core.process', verbose_name='Proceso relacionado')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_objectives', to='core.site', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Objetivo de calidad',
                'verbose_name_plural': 'Objetivos de calidad',
                'ordering': ['due_date'],
            },
        ),
    ]
