# Generated by Django 5.0.14 on 2026-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_qualityobjective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityobjective',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('BIMONTHLY', 'Bimestral'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual'), ('OTHER', 'Otra')], help_text='Frecuencia de medicion del objetivo', max_length=20, verbose_name='Frecuencia'),
        ),
    ]
