# Generated by Django 5.0.14 on 2026-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_internal_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalaudit',
            name='audit_type',
            field=models.CharField(choices=[('INTERNAL', 'Interna'), ('EXTERNAL', 'Externa')], default='INTERNAL', max_length=10, verbose_name='Tipo de auditoria'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='audits/plan/', verbose_name='Archivo de planificacion'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='audits/report/', verbose_name='Archivo de informe'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='team_cv_file',
            field=models.FileField(blank=True, null=True, upload_to='audits/team_cv/', verbose_name='CV del equipo auditor'),
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='finding_type',
            field=models.CharField(choices=[('OBSERVATION', 'Observacion'), ('NONCONFORMITY', 'No conformidad'), ('OPPORTUNITY', 'Oportunidad de mejora')], max_length=20, verbose_name='Tipo de hallazgo'),
        ),
    ]
