# Generated by Django 5.0.14 on 2026-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_internalaudit_audit_type_internalaudit_plan_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='finding_type',
            field=models.CharField(choices=[('AREA_OF_CONCERN', 'Área de preocupación'), ('IMPROVEMENT_OPPORTUNITY', 'Oportunidad de mejora'), ('NONCONFORMITY', 'No conformidad')], max_length=23, verbose_name='Tipo de hallazgo'),
        ),
    ]
