# Generated by Django 5.0.14 on 2026-02-16 15:56

from django.db import migrations


def map_finding_types_forward(apps, schema_editor):
    """Map old finding type values to new ones."""
    AuditFinding = apps.get_model('core', 'AuditFinding')
    
    # OBSERVATION -> AREA_OF_CONCERN
    AuditFinding.objects.filter(finding_type='OBSERVATION').update(finding_type='AREA_OF_CONCERN')
    
    # OPPORTUNITY -> IMPROVEMENT_OPPORTUNITY
    AuditFinding.objects.filter(finding_type='OPPORTUNITY').update(finding_type='IMPROVEMENT_OPPORTUNITY')
    
    # NONCONFORMITY stays the same


def map_finding_types_backward(apps, schema_editor):
    """Reverse the mapping (for backwards compatibility)."""
    AuditFinding = apps.get_model('core', 'AuditFinding')
    
    # AREA_OF_CONCERN -> OBSERVATION
    AuditFinding.objects.filter(finding_type='AREA_OF_CONCERN').update(finding_type='OBSERVATION')
    
    # IMPROVEMENT_OPPORTUNITY -> OPPORTUNITY
    AuditFinding.objects.filter(finding_type='IMPROVEMENT_OPPORTUNITY').update(finding_type='OPPORTUNITY')
    
    # NONCONFORMITY stays the same


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_auditfinding_finding_type'),
    ]

    operations = [
        migrations.RunPython(map_finding_types_forward, map_finding_types_backward),
    ]
