# Generated by Django 5.0.14 on 2026-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_map_finding_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='capaaction',
            name='effectiveness_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de evaluacion de eficacia'),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='effectiveness_notes',
            field=models.TextField(blank=True, help_text='Detalles sobre la evaluacion de eficacia de la accion', verbose_name='Notas de eficacia'),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='effectiveness_result',
            field=models.CharField(blank=True, choices=[('EFFECTIVE', 'Efectiva'), ('NOT_EFFECTIVE', 'No efectiva')], max_length=20, null=True, verbose_name='Resultado de eficacia'),
        ),
    ]
