# Generated by Django 5.0.14 on 2026-02-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_capaaction_effectiveness_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capaaction',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capa_actions', to='core.auditfinding', verbose_name='Hallazgo asociado'),
        ),
        migrations.AlterField(
            model_name='capaaction',
            name='no_conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capa_actions', to='core.noconformity', verbose_name='No conformidad'),
        ),
    ]
