# Generated by Django 5.2.11 on 2026-03-02 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_capaaction_finding_alter_capaaction_no_conformity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name='Fecha de revision')),
                ('attendees', models.TextField(blank=True, help_text='Lista de asistentes a la reunion', verbose_name='Asistentes')),
                ('audit_results_summary', models.TextField(blank=True, help_text='Resumen de resultados de auditorias internas y externas', verbose_name='Resultados de auditorias')),
                ('customer_feedback_summary', models.TextField(blank=True, help_text='Resumen de retroalimentacion de clientes y partes interesadas', verbose_name='Retroalimentacion del cliente')),
                ('process_performance_summary', models.TextField(blank=True, help_text='Resumen del desempeno y conformidad de productos/servicios', verbose_name='Desempeno de procesos')),
                ('nonconformities_status_summary', models.TextField(blank=True, help_text='Estado de no conformidades y acciones correctivas/preventivas', verbose_name='Estado de no conformidades')),
                ('risk_opportunity_status_summary', models.TextField(blank=True, help_text='Estado de riesgos y oportunidades identificados', verbose_name='Estado de riesgos y oportunidades')),
                ('supplier_performance_summary', models.TextField(blank=True, help_text='Resumen del desempeno de proveedores externos', verbose_name='Desempeno de proveedores')),
                ('resource_adequacy_summary', models.TextField(blank=True, help_text='Adecuacion de recursos disponibles', verbose_name='Adecuacion de recursos')),
                ('improvement_actions', models.TextField(blank=True, help_text='Decisiones y acciones relacionadas con oportunidades de mejora', verbose_name='Oportunidades de mejora')),
                ('changes_to_qms', models.TextField(blank=True, help_text='Cambios necesarios al Sistema de Gestion de Calidad', verbose_name='Cambios al SGC')),
                ('resource_needs', models.TextField(blank=True, help_text='Necesidades de recursos identificadas', verbose_name='Necesidades de recursos')),
                ('meeting_minutes_file', models.FileField(blank=True, null=True, upload_to='management_reviews/', verbose_name='Acta de reunion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_reviews_as_chair', to=settings.AUTH_USER_MODEL, verbose_name='Presidente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_reviews', to='core.organization', verbose_name='Organizacion')),
            ],
            options={
                'verbose_name': 'Revision por la Direccion',
                'verbose_name_plural': 'Revisiones por la Direccion',
                'ordering': ['-review_date'],
            },
        ),
    ]
