# Generated by Django 5.2.11 on 2026-03-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_managementreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], max_length=20, verbose_name='Frecuencia de medición')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor meta')),
                ('comparison_type', models.CharField(choices=[('GREATER_EQUAL', 'Mayor o igual a'), ('LESS_EQUAL', 'Menor o igual a')], max_length=20, verbose_name='Tipo de comparación')),
                ('unit', models.CharField(blank=True, help_text='Por ejemplo: %, puntos, días, etc.', max_length=20, verbose_name='Unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_indicators', to='core.organization', verbose_name='Organización')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_indicators', to='core.process', verbose_name='Proceso relacionado')),
            ],
            options={
                'verbose_name': 'Indicador de Calidad',
                'verbose_name_plural': 'Indicadores de Calidad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(verbose_name='Fecha de medición')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor medido')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.qualityindicator', verbose_name='Indicador')),
            ],
            options={
                'verbose_name': 'Medición de Indicador',
                'verbose_name_plural': 'Mediciones de Indicador',
                'ordering': ['-measurement_date'],
            },
        ),
    ]
