# Generated by Django 5.2.11 on 2026-03-02 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_qualityindicator_indicatormeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonconformingOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='PNC-2026-001, PNC-2026-002, etc.', max_length=20, unique=True, verbose_name='Código')),
                ('detected_at', models.DateField(verbose_name='Fecha de detección')),
                ('product_or_service', models.CharField(help_text='Ejemplo: Tolva 26tn, Servicio postventa', max_length=200, verbose_name='Producto/Servicio')),
                ('description', models.TextField(verbose_name='Descripción del no cumplimiento')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad')),
                ('severity', models.CharField(choices=[('MINOR', 'Menor'), ('MAJOR', 'Mayor'), ('CRITICAL', 'Crítica')], default='MAJOR', max_length=20, verbose_name='Severidad')),
                ('disposition', models.CharField(blank=True, choices=[('REWORK', 'Retrabajo'), ('REPAIR', 'Reparación'), ('SCRAP', 'Descarte'), ('CONCESSION', 'Concesión/Aceptación'), ('RETURN', 'Devolución'), ('OTHER', 'Otro')], help_text='Acción tomada sobre el producto/servicio no conforme', max_length=20, null=True, verbose_name='Disposición')),
                ('disposition_notes', models.TextField(blank=True, help_text='Detalles y evidencia de la disposición (obligatorio para CONCESSION)', verbose_name='Notas sobre disposición')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_TREATMENT', 'En tratamiento'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='nonconforming_outputs/', verbose_name='Archivo de evidencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_nonconforming_outputs', to=settings.AUTH_USER_MODEL, verbose_name='Detectado por')),
                ('linked_nc', models.ForeignKey(blank=True, help_text='Opcionalmente linkear a NoConformity del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconforming_outputs', to='core.noconformity', verbose_name='NC vinculada')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconforming_outputs', to='core.organization', verbose_name='Organización')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconforming_outputs', to='core.process', verbose_name='Proceso relacionado')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treated_nonconforming_outputs', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del tratamiento')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconforming_outputs', to='core.site', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Producto/Servicio No Conforme',
                'verbose_name_plural': 'Productos/Servicios No Conformes',
                'ordering': ['-detected_at'],
            },
        ),
    ]
