# Generated by Django 5.2.11 on 2026-03-02 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_nonconformingoutput'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('cuit', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('category', models.CharField(choices=[('RAW_MATERIAL', 'Materia Prima'), ('SERVICE', 'Servicio'), ('OUTSOURCED_PROCESS', 'Proceso Tercerizado'), ('OTHER', 'Otro')], max_length=30, verbose_name='Categoría')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Contacto')),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobado'), ('CONDITIONAL', 'Aprobado Condicionalmente'), ('NOT_APPROVED', 'No Aprobado'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('last_evaluation_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Última Evaluación')),
                ('next_evaluation_date', models.DateField(blank=True, null=True, verbose_name='Próxima Evaluación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='core.organization', verbose_name='Organización')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.process', verbose_name='Proceso Relacionado')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.site', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(verbose_name='Fecha de Evaluación')),
                ('quality_score', models.PositiveSmallIntegerField(help_text='Calidad de productos/servicios (1=Muy malo, 5=Excelente)', verbose_name='Puntuación Calidad (1-5)')),
                ('delivery_score', models.PositiveSmallIntegerField(help_text='Cumplimiento de plazos de entrega (1=Muy malo, 5=Excelente)', verbose_name='Puntuación Entrega (1-5)')),
                ('price_score', models.PositiveSmallIntegerField(help_text='Relación precio-calidad (1=Muy caro, 5=Muy competitivo)', verbose_name='Puntuación Precio (1-5)')),
                ('overall_score', models.DecimalField(decimal_places=2, editable=False, max_digits=4, verbose_name='Puntuación General')),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprobado'), ('CONDITIONAL', 'Aprobado Condicionalmente'), ('NOT_APPROVED', 'No Aprobado')], max_length=20, verbose_name='Decisión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='supplier_evaluations/', verbose_name='Archivo de Evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_evaluations', to='core.organization', verbose_name='Organización')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Evaluación de Proveedor',
                'verbose_name_plural': 'Evaluaciones de Proveedor',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_supplier_per_org'),
        ),
    ]
