# Generated by Django 5.2.11 on 2026-03-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_supplier_supplierevaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Competencia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('required_for_position', models.CharField(max_length=150, verbose_name='Requerida para puesto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencies', to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('position', models.CharField(max_length=150, verbose_name='Puesto')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Departamento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_required', models.PositiveSmallIntegerField(default=1, verbose_name='Nivel requerido')),
                ('level_current', models.PositiveSmallIntegerField(default=1, verbose_name='Nivel actual')),
                ('is_gap', models.BooleanField(default=False, verbose_name='Brecha')),
                ('last_evaluated', models.DateField(blank=True, null=True, verbose_name='Última evaluación')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_competencies', to='core.competency', verbose_name='Competencia')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_competencies', to='core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Competencia por Empleado',
                'verbose_name_plural': 'Competencias por Empleado',
                'ordering': ['competency__name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('provider', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('training_date', models.DateField(verbose_name='Fecha de capacitación')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='trainings/', verbose_name='Archivo de evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-training_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('PLANNED', 'Planificada'), ('COMPLETED', 'Completada'), ('FAILED', 'No aprobada')], default='PLANNED', max_length=20, verbose_name='Estado de finalización')),
                ('effectiveness_evaluated', models.BooleanField(default=False, verbose_name='Eficacia evaluada')),
                ('effectiveness_result', models.CharField(blank=True, choices=[('EFFECTIVE', 'Eficaz'), ('NOT_EFFECTIVE', 'No eficaz')], max_length=20, verbose_name='Resultado de eficacia')),
                ('evaluation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de evaluación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendances', to='core.employee', verbose_name='Empleado')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.training', verbose_name='Capacitación')),
            ],
            options={
                'verbose_name': 'Asistencia de Capacitación',
                'verbose_name_plural': 'Asistencias de Capacitación',
                'ordering': ['-training__training_date', 'employee__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'required_for_position'), name='unique_competency_name_position_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_employee_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeecompetency',
            constraint=models.UniqueConstraint(fields=('employee', 'competency'), name='unique_employee_competency'),
        ),
        migrations.AddConstraint(
            model_name='trainingattendance',
            constraint=models.UniqueConstraint(fields=('training', 'employee'), name='unique_training_attendance'),
        ),
    ]
