# Generated by Django 5.2.11 on 2026-03-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_competency_employee_employeecompetency_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontext',
            name='qms_scope',
            field=models.TextField(blank=True, verbose_name='Alcance del SGC'),
        ),
    ]
