# Generated by Django 5.2.11 on 2026-03-07 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_organizationcontext_qms_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierevaluation',
            name='delivery_score',
            field=models.PositiveSmallIntegerField(help_text='Cumplimiento de plazos de entrega (1=Muy malo, 5=Excelente)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación Entrega (1-5)'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='price_score',
            field=models.PositiveSmallIntegerField(help_text='Relación precio-calidad (1=Muy caro, 5=Muy competitivo)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación Precio (1-5)'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='quality_score',
            field=models.PositiveSmallIntegerField(help_text='Calidad de productos/servicios (1=Muy malo, 5=Excelente)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación Calidad (1-5)'),
        ),
    ]
