# Generated by Django 5.2.11 on 2026-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_supplierevaluation_delivery_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformity',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM_TEXT', 'Telegram texto'), ('TELEGRAM_AUDIO', 'Telegram audio')], default='WEB', max_length=20, verbose_name='Origen de carga'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM_TEXT', 'Telegram texto'), ('TELEGRAM_AUDIO', 'Telegram audio')], default='WEB', max_length=20, verbose_name='Origen de carga'),
        ),
    ]
