# Generated by Django 5.2.11 on 2026-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_noconformity_source_nonconformingoutput_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformity',
            name='classification',
            field=models.CharField(blank=True, choices=[('PROBLEM', 'Problema'), ('FINDING', 'Hallazgo')], help_text='Problema o Hallazgo', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='impacts_procedure',
            field=models.BooleanField(default=False, verbose_name='Impacta en el Procedimiento'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='impacts_system',
            field=models.BooleanField(default=False, verbose_name='Impacta en el Sistema'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='norm_clause',
            field=models.CharField(blank=True, help_text='Ej: ISO 9001:2015 - 8.4, Procedimiento FP-09', max_length=100, verbose_name='Norma y Cláusula'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='observed_during',
            field=models.CharField(blank=True, help_text='Ej: Control Dimensional, Inspección Final, Auditoría Interna', max_length=100, verbose_name='Observada durante'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='work_order',
            field=models.CharField(blank=True, help_text='Ej: Plan Nº 53, OT-2026-001', max_length=100, verbose_name='Orden de Trabajo'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='classification',
            field=models.CharField(blank=True, choices=[('PROBLEM', 'Problema'), ('FINDING', 'Hallazgo')], help_text='Problema o Hallazgo', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='impacts_procedure',
            field=models.BooleanField(default=False, verbose_name='Impacta en el Procedimiento'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='impacts_system',
            field=models.BooleanField(default=False, verbose_name='Impacta en el Sistema'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='norm_clause',
            field=models.CharField(blank=True, help_text='Ej: ISO 9001:2015 - 8.4, Procedimiento FP-09', max_length=100, verbose_name='Norma y Cláusula'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='observed_during',
            field=models.CharField(blank=True, help_text='Ej: Control Dimensional, Inspección Final, Auditoría Interna', max_length=100, verbose_name='Observada durante'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='work_order',
            field=models.CharField(blank=True, help_text='Ej: Plan Nº 53, OT-2026-001', max_length=100, verbose_name='Orden de Trabajo'),
        ),
    ]
