# Generated by Django 5.2.11 on 2026-03-08 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_noconformity_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformity',
            name='organization_representative',
            field=models.ForeignKey(blank=True, help_text='Persona que representa a la organización en este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_org_representative', to=settings.AUTH_USER_MODEL, verbose_name='Representante de la Organización'),
        ),
        migrations.AddField(
            model_name='noconformity',
            name='verification_representative',
            field=models.ForeignKey(blank=True, help_text='Persona que representa la verificación de acciones correctivas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_verif_representative', to=settings.AUTH_USER_MODEL, verbose_name='Representante de Verificación'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='organization_representative',
            field=models.ForeignKey(blank=True, help_text='Persona que representa a la organización en este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_org_representative', to=settings.AUTH_USER_MODEL, verbose_name='Representante de la Organización'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='verification_representative',
            field=models.ForeignKey(blank=True, help_text='Persona que representa la verificación de acciones correctivas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_verif_representative', to=settings.AUTH_USER_MODEL, verbose_name='Representante de Verificación'),
        ),
    ]
