# Generated by Django 5.2.11 on 2026-03-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_noconformity_organization_representative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformingoutput',
            name='corrective_action',
            field=models.TextField(blank=True, help_text='Que se hizo para resolver este problema y prevenir la recurrencia', verbose_name='Acción correctiva'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Responsable asignado al registro R-05-01', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nonconforming_outputs', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='root_cause_analysis',
            field=models.TextField(blank=True, help_text='¿Qué falló en el sistema para permitir que ocurra este PNC?', verbose_name='Análisis de causa raíz'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='title',
            field=models.CharField(blank=True, help_text='Resumen breve del problema o hallazgo', max_length=200, verbose_name='Descripción del problema o hallazgo'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='nonconformingoutput',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Comentarios del auditor'),
        ),
    ]
