# Generated by Django 5.2.11 on 2026-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_nonconformingoutput_corrective_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='cuit',
            field=models.CharField(blank=True, help_text='CUIT/CUIL del cliente o parte interesada', max_length=20, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50, verbose_name='Teléfono'),
        ),
    ]
