# Generated by Django 5.2.11 on 2026-03-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_stakeholder_cuit_stakeholder_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='IC-2026-001, IC-2026-002, etc.', max_length=20, unique=True, verbose_name='Código')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('customer_name', models.CharField(blank=True, help_text='Si el cliente no está en Partes Interesadas, escribir nombre acá', max_length=200, verbose_name='Nombre del Cliente')),
                ('project', models.CharField(blank=True, help_text='Ej: Pala M1001, Retroexcavadora RT-210, Acoplado 1 Eje', max_length=200, verbose_name='Proyecto / Producto')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('MAIL', 'Mail'), ('PHONE', 'Llamada Telefónica'), ('IN_PERSON', 'Presencial'), ('DEALER', 'Concesionario'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('OTHER', 'Otro')], max_length=20, verbose_name='Canal')),
                ('interaction_type', models.CharField(choices=[('QUERY', 'Consulta'), ('CLAIM', 'Reclamo'), ('SUGGESTION', 'Sugerencia'), ('COMPLIMENT', 'Felicitación'), ('MENTION', 'Mención'), ('AFTER_SALES', 'Postventa')], max_length=20, verbose_name='Tipo de Interacción')),
                ('topic', models.CharField(choices=[('QUALITY', 'Calidad'), ('DELIVERY', 'Plazo'), ('PRICE', 'Precio'), ('SERVICE', 'Servicio'), ('PERFORMANCE', 'Funcionamiento'), ('DESIGN', 'Diseño'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tema')),
                ('perception', models.CharField(choices=[('POSITIVE', 'Positiva'), ('NEUTRAL', 'Neutra'), ('NEGATIVE', 'Negativa')], max_length=20, verbose_name='Percepción')),
                ('perception_score', models.IntegerField(default=0, editable=False, help_text='1=Positiva, 0=Neutra, -1=Negativa', verbose_name='Score de Percepción')),
                ('impact', models.CharField(choices=[('HIGH', 'Alto'), ('MEDIUM', 'Medio'), ('LOW', 'Bajo')], max_length=20, verbose_name='Impacto')),
                ('requires_action', models.BooleanField(default=False, verbose_name='Requiere Acción')),
                ('responsible', models.CharField(blank=True, choices=[('SALES', 'Ventas'), ('AFTER_SALES', 'Postventa'), ('PURCHASING', 'Compras'), ('ADMIN', 'Administración'), ('DESIGN', 'Diseño'), ('PRODUCTION', 'Producción')], max_length=20, verbose_name='Responsable')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('FOLLOW_UP', 'Seguimiento'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('result', models.CharField(blank=True, choices=[('SIMPLE_QUERY', 'Consulta Simple'), ('COMPLIMENT', 'Felicitación'), ('PREVENTIVE_ACTION', 'Acción Preventiva'), ('CORRECTIVE_ACTION', 'Acción Correctiva'), ('DERIVES_NC', 'Deriva No Conformidad'), ('CLAIM_RESOLVED', 'Reclamo Resuelto')], max_length=25, verbose_name='Resultado')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM_TEXT', 'Telegram texto'), ('TELEGRAM_AUDIO', 'Telegram audio')], default='WEB', max_length=20, verbose_name='Origen de carga')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('customer', models.ForeignKey(blank=True, help_text='Seleccionar parte interesada (cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_interactions', to='core.stakeholder', verbose_name='Cliente')),
                ('linked_nc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_interactions', to='core.noconformity', verbose_name='NC Asociada')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_interactions', to='core.organization', verbose_name='Organización')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_interactions', to='core.site', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Interacción con Cliente',
                'verbose_name_plural': 'Interacciones con Clientes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
