# Generated by Django 5.2.11 on 2026-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_customerinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='client_objections',
            field=models.TextField(blank=True, verbose_name='Objeciones del Cliente'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='communication_objective',
            field=models.TextField(blank=True, verbose_name='Objetivo de la Comunicación'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Conclusión Final'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Nombre de la persona con quien se comunicó', max_length=200, verbose_name='Persona de Contacto'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='next_communication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Comunicación - Fecha y Hora'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='next_communication_responsible',
            field=models.CharField(blank=True, max_length=200, verbose_name='Próxima Comunicación - Responsable'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='proposals',
            field=models.TextField(blank=True, verbose_name='Propuestas Realizadas'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='tasks_to_do',
            field=models.TextField(blank=True, verbose_name='Tareas a Realizar'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
    ]
