# Generated by Django 5.2.11 on 2026-03-11 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_customerinteraction_client_objections_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='SAT-2026-001, SAT-2026-002, etc.', max_length=20, unique=True, verbose_name='Código')),
                ('report_date', models.DateField(verbose_name='Fecha del Informe')),
                ('period_start', models.DateField(verbose_name='Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fin del Período')),
                ('period_label', models.CharField(help_text='Ej: Octubre a Diciembre de 2025', max_length=100, verbose_name='Período Evaluado')),
                ('total_interactions', models.IntegerField(default=0, editable=False, verbose_name='Total de Registros')),
                ('count_query', models.IntegerField(default=0, editable=False, verbose_name='Consultas')),
                ('count_claim', models.IntegerField(default=0, editable=False, verbose_name='Reclamos')),
                ('count_suggestion', models.IntegerField(default=0, editable=False, verbose_name='Sugerencias')),
                ('count_compliment', models.IntegerField(default=0, editable=False, verbose_name='Felicitaciones')),
                ('count_after_sales', models.IntegerField(default=0, editable=False, verbose_name='Postventa')),
                ('count_mention', models.IntegerField(default=0, editable=False, verbose_name='Menciones')),
                ('count_positive', models.IntegerField(default=0, editable=False, verbose_name='Percepción Positiva')),
                ('count_neutral', models.IntegerField(default=0, editable=False, verbose_name='Percepción Neutra')),
                ('count_negative', models.IntegerField(default=0, editable=False, verbose_name='Percepción Negativa')),
                ('count_high_impact', models.IntegerField(default=0, editable=False, verbose_name='Impacto Alto')),
                ('count_medium_impact', models.IntegerField(default=0, editable=False, verbose_name='Impacto Medio')),
                ('count_low_impact', models.IntegerField(default=0, editable=False, verbose_name='Impacto Bajo')),
                ('count_whatsapp', models.IntegerField(default=0, editable=False, verbose_name='WhatsApp')),
                ('count_mail', models.IntegerField(default=0, editable=False, verbose_name='Mail')),
                ('count_phone', models.IntegerField(default=0, editable=False, verbose_name='Llamada')),
                ('count_in_person', models.IntegerField(default=0, editable=False, verbose_name='Presencial')),
                ('count_social', models.IntegerField(default=0, editable=False, verbose_name='Redes Sociales')),
                ('satisfaction_index', models.FloatField(default=0, editable=False, verbose_name='Índice Global de Satisfacción (%)')),
                ('claim_percentage', models.FloatField(default=0, editable=False, verbose_name='% Reclamos sobre Total')),
                ('avg_resolution_days', models.FloatField(default=0, editable=False, verbose_name='Tiempo Promedio Resolución (días)')),
                ('general_status', models.TextField(blank=True, verbose_name='Estado General de la Satisfacción del Cliente')),
                ('trend_vs_previous', models.TextField(blank=True, verbose_name='Tendencia con Respecto al Período Anterior')),
                ('general_situation', models.TextField(blank=True, help_text='Satisfactoria / A mejorar / Crítica - Comentarios', verbose_name='Situación General')),
                ('observed_trends', models.TextField(blank=True, verbose_name='Tendencias Observadas')),
                ('comparison_previous', models.TextField(blank=True, verbose_name='Comparación con Períodos Anteriores')),
                ('deviations', models.TextField(blank=True, verbose_name='Identificación de Desvíos')),
                ('improvement_opportunities', models.TextField(blank=True, verbose_name='Oportunidades de Mejora')),
                ('satisfaction_result', models.CharField(blank=True, choices=[('ADEQUATE', 'Adecuada'), ('PARTIALLY', 'Parcialmente adecuada'), ('NOT_ADEQUATE', 'No adecuada')], max_length=20, verbose_name='Resultado de Satisfacción')),
                ('justification', models.TextField(blank=True, verbose_name='Justificación Breve')),
                ('action_required', models.CharField(blank=True, choices=[('NONE', 'No se requieren acciones'), ('PREVENTIVE', 'Se requieren acciones preventivas'), ('CORRECTIVE', 'Se requieren acciones correctivas')], max_length=20, verbose_name='Acciones Requeridas')),
                ('actions_description', models.TextField(blank=True, verbose_name='Descripción de Acciones')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='Análisis generado por IA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_satisfaction_reports', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_reports', to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Informe de Satisfacción',
                'verbose_name_plural': 'Informes de Satisfacción',
                'ordering': ['-period_end'],
            },
        ),
    ]
