from django.urls import path

from apps.core.views import (
    context_detail,
    context_edit,
    capa_action_create,
    capa_action_create_from_finding,
    capa_action_edit,
    nc_create,
    nc_detail,
        nc_pdf,
    nc_edit,
    nc_list,
    risk_create,
    risk_dashboard,
    risk_detail,
    risk_edit,
    risk_list,
    stakeholder_create,
    stakeholder_detail,
    stakeholder_edit,
    stakeholder_list,
    quality_objective_list,
    quality_objective_detail,
    quality_objective_create,
    quality_objective_edit,
    audit_list,
    audit_detail,
    audit_create,
    audit_edit,
    audit_checklist,
    audit_finding_create,
    audit_finding_edit,
    audit_finding_create_nc,
    audit_question_list,
    audit_question_create,
    audit_question_edit,
    audit_question_toggle,
    management_review_list,
    management_review_create,
    management_review_detail,
    management_review_edit,
    indicator_list,
    indicator_detail,
    indicator_create,
    indicator_edit,
    measurement_create,
    nonconforming_output_list,
    nonconforming_output_detail,
    pnc_pdf,
    nonconforming_output_create,
    nonconforming_output_edit,
    nonconforming_output_create_nc,
    supplier_list,
    supplier_detail,
    supplier_create,
    supplier_edit,
    supplier_evaluation_create,
    interaction_list,
    interaction_detail,
    interaction_pdf,
    interaction_create,
    interaction_edit,
    satisfaction_report_list,
    satisfaction_report_detail,
    satisfaction_report_create,
    satisfaction_report_edit,
    satisfaction_report_generate_ai,
    satisfaction_report_pdf,
    dashboard_home,
    dashboard_card_nc,
    dashboard_card_capa,
    dashboard_card_indicadores,
    dashboard_card_indicators,
    dashboard_card_pnc,
    dashboard_card_suppliers,
    dashboard_card_interactions,
    dashboard_card_auditorias,
    dashboard_card_audits,
    dashboard_chart_nc_trend,
    dashboard_chart_capa_status,
    dashboard_chart_indicator_status,
    dashboard_chart_pnc_severity,
)
from apps.core.competency_views import (
    employee_list,
    employee_detail,
    employee_add_competency,
    employee_create,
    employee_edit,
    competency_list,
    competency_create,
    competency_edit,
    training_list,
    training_detail,
    training_create,
    training_edit,
    training_attendance_create,
    dashboard_card_competencies,
)

app_name = "core"

urlpatterns = [
    path("employees/", employee_list, name="employee_list"),
    path("employees/new/", employee_create, name="employee_create"),
    path("employees/<int:pk>/", employee_detail, name="employee_detail"),
    path("employees/<int:pk>/add-competency/", employee_add_competency, name="employee_add_competency"),
    path("employees/<int:pk>/edit/", employee_edit, name="employee_edit"),

    path("competencies/", competency_list, name="competency_list"),
    path("competencies/new/", competency_create, name="competency_create"),
    path("competencies/<int:pk>/edit/", competency_edit, name="competency_edit"),

    path("trainings/", training_list, name="training_list"),
    path("trainings/new/", training_create, name="training_create"),
    path("trainings/<int:pk>/", training_detail, name="training_detail"),
    path("trainings/<int:pk>/edit/", training_edit, name="training_edit"),

    path("training-attendance/new/", training_attendance_create, name="training_attendance_create"),

    path("context/", context_detail, name="context_detail"),
    path("context/edit/", context_edit, name="context_edit"),
    path("stakeholders/", stakeholder_list, name="stakeholder_list"),
    path("stakeholders/new/", stakeholder_create, name="stakeholder_new"),
    path("stakeholders/<int:pk>/", stakeholder_detail, name="stakeholder_detail"),
    path("stakeholders/<int:pk>/edit/", stakeholder_edit, name="stakeholder_edit"),
    path("risks/", risk_list, name="risk_list"),
    path("risks/dashboard/", risk_dashboard, name="risk_dashboard"),
    path("risks/new/", risk_create, name="risk_new"),
    path("risks/<int:pk>/", risk_detail, name="risk_detail"),
    path("risks/<int:pk>/edit/", risk_edit, name="risk_edit"),
    path("nc/", nc_list, name="nc_list"),
    path("nc/new/", nc_create, name="nc_new"),
    path("nc/<int:pk>/", nc_detail, name="nc_detail"),
    path("nc/<int:pk>/edit/", nc_edit, name="nc_edit"),
        path("nc/<int:pk>/pdf/", nc_pdf, name="nc_pdf"),
    path("nc/<int:nc_id>/actions/new/", capa_action_create, name="capa_action_create"),
    path("capa/<int:action_id>/edit/", capa_action_edit, name="capa_action_edit"),
    path("objectives/", quality_objective_list, name="quality_objective_list"),
    path("objectives/new/", quality_objective_create, name="quality_objective_new"),
    path("objectives/<int:pk>/", quality_objective_detail, name="quality_objective_detail"),
    path("objectives/<int:pk>/edit/", quality_objective_edit, name="quality_objective_edit"),
    path("audits/", audit_list, name="audit_list"),
    path("audits/new/", audit_create, name="audit_new"),
    path("audits/<int:pk>/", audit_detail, name="audit_detail"),
    path("audits/<int:pk>/edit/", audit_edit, name="audit_edit"),
    path("audits/<int:pk>/checklist/", audit_checklist, name="audit_checklist"),
    path("audits/<int:pk>/findings/new/", audit_finding_create, name="audit_finding_new"),
    path("audits/findings/<int:pk>/edit/", audit_finding_edit, name="audit_finding_edit"),
    path("audits/findings/<int:pk>/create-nc/", audit_finding_create_nc, name="audit_finding_create_nc"),
    path("audits/findings/<int:pk>/actions/new/", capa_action_create_from_finding, name="audit_finding_action_new"),
    path("audits/questions/", audit_question_list, name="audit_question_list"),
    path("audits/questions/new/", audit_question_create, name="audit_question_new"),
    path("audits/questions/<int:pk>/edit/", audit_question_edit, name="audit_question_edit"),
    path("audits/questions/<int:pk>/toggle/", audit_question_toggle, name="audit_question_toggle"),
    path("management-reviews/", management_review_list, name="management_review_list"),
    path("management-reviews/new/", management_review_create, name="management_review_new"),
    path("management-reviews/<int:pk>/", management_review_detail, name="management_review_detail"),
    path("management-reviews/<int:pk>/edit/", management_review_edit, name="management_review_edit"),
    path("management-reviews/", management_review_list, name="review_list"),
    path("management-reviews/new/", management_review_create, name="review_new"),
    path("management-reviews/<int:pk>/", management_review_detail, name="review_detail"),
    path("management-reviews/<int:pk>/edit/", management_review_edit, name="review_edit"),
    path("indicators/", indicator_list, name="indicator_list"),
    path("indicators/new/", indicator_create, name="indicator_new"),
    path("indicators/<int:pk>/", indicator_detail, name="indicator_detail"),
    path("indicators/<int:pk>/edit/", indicator_edit, name="indicator_edit"),
    path("indicators/<int:indicator_pk>/measurements/new/", measurement_create, name="measurement_new"),
    
    # NonconformingOutput (ISO 8.7)
    path("pnc/", nonconforming_output_list, name="nonconforming_output_list"),
    path("pnc/new/", nonconforming_output_create, name="nonconforming_output_new"),
    path("pnc/<int:pk>/", nonconforming_output_detail, name="nonconforming_output_detail"),
    path("pnc/<int:pk>/edit/", nonconforming_output_edit, name="nonconforming_output_edit"),
    path("pnc/<int:pk>/pdf/", pnc_pdf, name="pnc_pdf"),
    path("pnc/<int:pk>/create-nc/", nonconforming_output_create_nc, name="nonconforming_output_create_nc"),
    
    # Supplier (ISO 8.4)
    path("suppliers/", supplier_list, name="supplier_list"),
    path("suppliers/new/", supplier_create, name="supplier_new"),
    path("suppliers/<int:pk>/", supplier_detail, name="supplier_detail"),
    path("suppliers/<int:pk>/edit/", supplier_edit, name="supplier_edit"),
    path("suppliers/<int:supplier_pk>/evaluations/new/", supplier_evaluation_create, name="supplier_evaluation_new"),

    # Interacciones con el Cliente (ISO 7.4, 9.1.2)
    path("interactions/", interaction_list, name="interaction_list"),
    path("interactions/new/", interaction_create, name="interaction_new"),
    path("interactions/<int:pk>/", interaction_detail, name="interaction_detail"),
    path("interactions/<int:pk>/pdf/", interaction_pdf, name="interaction_pdf"),
    path("interactions/<int:pk>/edit/", interaction_edit, name="interaction_edit"),

    # Informes de Satisfacción (ISO 9.1.2)
    path("satisfaction/", satisfaction_report_list, name="satisfaction_report_list"),
    path("satisfaction/new/", satisfaction_report_create, name="satisfaction_report_new"),
    path("satisfaction/<int:pk>/", satisfaction_report_detail, name="satisfaction_report_detail"),
    path("satisfaction/<int:pk>/edit/", satisfaction_report_edit, name="satisfaction_report_edit"),
    path("satisfaction/<int:pk>/generate-ai/", satisfaction_report_generate_ai, name="satisfaction_report_generate_ai"),
    path("satisfaction/<int:pk>/pdf/", satisfaction_report_pdf, name="satisfaction_report_pdf"),

    # Dashboard (DASH-01)
    path("dashboard/", dashboard_home, name="dashboard_home"),
    path("dashboard/card/nc/", dashboard_card_nc, name="dashboard_card_nc"),
    path("dashboard/card/capa/", dashboard_card_capa, name="dashboard_card_capa"),
    path("dashboard/card/indicadores/", dashboard_card_indicadores, name="dashboard_card_indicadores"),
    path("dashboard/card/indicators/", dashboard_card_indicators, name="dashboard_card_indicators"),
    path("dashboard/card/pnc/", dashboard_card_pnc, name="dashboard_card_pnc"),
    path("dashboard/card/suppliers/", dashboard_card_suppliers, name="dashboard_card_suppliers"),
    path("dashboard/card/interactions/", dashboard_card_interactions, name="dashboard_card_interactions"),
    path("dashboard/card/competencies/", dashboard_card_competencies, name="dashboard_card_competencies"),
    path("dashboard/card/auditorias/", dashboard_card_auditorias, name="dashboard_card_auditorias"),
    path("dashboard/card/audits/", dashboard_card_audits, name="dashboard_card_audits"),
    
    # Dashboard Charts (DASH-03)
    path("dashboard/chart/nc-trend/", dashboard_chart_nc_trend, name="dashboard_chart_nc_trend"),
    path("dashboard/chart/capa-status/", dashboard_chart_capa_status, name="dashboard_chart_capa_status"),
    path("dashboard/chart/indicator-status/", dashboard_chart_indicator_status, name="dashboard_chart_indicator_status"),
    path("dashboard/chart/pnc-severity/", dashboard_chart_pnc_severity, name="dashboard_chart_pnc_severity"),
]
